#!/usr/bin/python3
#
# This script checks whether fermat keys have any other primes
# between their p and q value.

import os
import pathlib
import sys

import badkeys
import gmpy2

xdir = sys.argv[1]

for fn in os.listdir(xdir):
    crt = pathlib.Path(f"{xdir}/{fn}").read_text(encoding="ascii", errors="replace")
    r = badkeys.detectandcheck(crt)
    p = int(r["results"]["fermat"]["p"])
    q = int(r["results"]["fermat"]["q"])
    if p > q:
        p, q = q, p
    for x in range(p + 1, q):
        if gmpy2.is_prime(x):
            print(f"prime found in {fn}")
